# Generated by Django 4.0.3 on 2022-04-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_rename_user_myuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='type',
            new_name='link',
        ),
    ]
